### ISSUE TITLE
Example bgp.rb example

### ISSUE THREAD

**Issue by ehayon** [zenvdeluca/net_healer#16]
Would it be possible for you to put up an example of how you are handling the bgp blackhole /32 advertisement in ruby? I see that you gitignore a actions-available/bgp.rb file. Would be helpful to see how this works since it looks like you're not using FNM for the /32 route advertisement.

**Comment by zenvdeluca** [comment]
I am not using FNM for the /32 route.
what bgp.rb does is a simple system call to add a /32 route entry such as 'ip route add blackhole 192.168.0.195/32 table 10'
then I use BIRD importing routes from the linux kernel and exporting to mitigation scrubbing center
